#!/usr/bin/env python3
"""
Live Betting Odds Integration Options for March Madness Predictions

ESPN's public API does not include betting odds. Here are viable alternatives:
"""

print("=" * 80)
print("LIVE BETTING ODDS INTEGRATION OPTIONS")
print("=" * 80)
print()

print("OPTION 1: The Odds API (RECOMMENDED)")
print("-" * 80)
print("Website: https://the-odds-api.com/")
print("Pricing: Free tier (500 requests/month) + Paid plans")
print()
print("Pros:")
print("  ✅ Aggregates odds from 40+ sportsbooks")
print("  ✅ Live updates every few minutes")
print("  ✅ NCAA Basketball coverage")
print("  ✅ Returns moneylines, spreads, totals")
print("  ✅ Simple REST API")
print()
print("Cons:")
print("  ⚠️  Limited free tier (500 requests/month)")
print("  💰 Paid plans start at $60/month for 5,000 requests")
print()
print("Example endpoint:")
print("  GET https://api.the-odds-api.com/v4/sports/basketball_ncaab/odds/")
print("  ?apiKey=YOUR_KEY&regions=us&markets=h2h,spreads,totals")
print()
print("Sample integration code:")
print('''
import requests

def fetch_live_odds():
    api_key = "YOUR_API_KEY"
    sport = "basketball_ncaab"
    url = f"https://api.the-odds-api.com/v4/sports/{sport}/odds/"
    
    params = {
        'apiKey': api_key,
        'regions': 'us',
        'markets': 'h2h,spreads,totals',
        'oddsFormat': 'american'
    }
    
    response = requests.get(url, params=params)
    return response.json()
''')
print()

print("=" * 80)
print("OPTION 2: ESPN BET API (if accessible)")
print("-" * 80)
print("Status: ESPN BET exists but no public API documented")
print()
print("Pros:")
print("  ✅ Would integrate with existing ESPN data")
print("  ✅ ESPN is already trusted source")
print()
print("Cons:")
print("  ❌ No documented public API")
print("  ❌ Would require web scraping (fragile)")
print("  ❌ Possible ToS violations")
print()

print("=" * 80)
print("OPTION 3: Action Network API")
print("-" * 80)
print("Website: https://www.actionnetwork.com/")
print("Status: Provides odds data, API availability unclear")
print()
print("Pros:")
print("  ✅ Comprehensive college basketball coverage")
print("  ✅ Professional odds tracking")
print()
print("Cons:")
print("  ⚠️  API access not clearly documented")
print("  ⚠️  May require business/media partnership")
print()

print("=" * 80)
print("OPTION 4: Manual CSV Upload")
print("-" * 80)
print("Process: Download daily from sportsbook, upload to data_files/")
print()
print("Pros:")
print("  ✅ Zero API costs")
print("  ✅ Full control over data source")
print("  ✅ No rate limits")
print()
print("Cons:")
print("  ❌ Manual daily work")
print("  ❌ Not real-time")
print("  ❌ Prone to human error")
print()

print("=" * 80)
print("OPTION 5: Web Scraping (DraftKings, FanDuel, etc.)")
print("-" * 80)
print("Process: Scrape odds from public sportsbook websites")
print()
print("Pros:")
print("  ✅ Free data")
print("  ✅ Current odds available")
print()
print("Cons:")
print("  ❌ Fragile (sites change frequently)")
print("  ❌ May violate Terms of Service")
print("  ❌ Can trigger IP blocks/CAPTCHAs")
print("  ❌ Requires ongoing maintenance")
print()

print("=" * 80)
print("RECOMMENDED IMPLEMENTATION PLAN")
print("=" * 80)
print()
print("SHORT TERM (Immediate):")
print("  1. Sign up for The Odds API free tier (500 requests/month)")
print("  2. Create fetch_live_odds.py module")
print("  3. Call once per day to update odds for upcoming games")
print("  4. Cache results to minimize API calls")
print()
print("MEDIUM TERM (If usage grows):")
print("  1. Upgrade to paid tier if needed")
print("  2. Implement smart caching/update logic")
print("  3. Only fetch odds for games within next 48 hours")
print()
print("LONG TERM (Scale):")
print("  1. Evaluate cost vs. value")
print("  2. Consider switching to direct sportsbook APIs if available")
print("  3. Build historical odds database for model training")
print()

print("=" * 80)
print("ESTIMATED COSTS FOR MARCH MADNESS SEASON")
print("=" * 80)
print()
print("Free Tier (The Odds API):")
print("  • 500 requests/month = ~16 requests/day")
print("  • Sufficient for: 1-2 daily updates of 50 games")
print("  • Cost: $0")
print()
print("Paid Tier:")
print("  • 5,000 requests/month = ~166 requests/day")
print("  • Sufficient for: Hourly updates throughout season")
print("  • Cost: $60/month")
print()
print("Tournament Only (March):")
print("  • Could use free tier for regular season")
print("  • Upgrade for March Madness month only")
print("  • Total cost: ~$60 for tournament")
print()

print("=" * 80)
print("NEXT STEPS")
print("=" * 80)
print()
print("1. Go to https://the-odds-api.com/")
print("2. Sign up for free API key")
print("3. I'll create the integration module:")
print("   - fetch_live_odds.py - pulls current odds")
print("   - Update predictions.py to use live odds")
print("   - Cache odds to minimize API calls")
print()
print("Would you like me to create this integration now?")
print("(You'll need to provide your API key)")
print()
